# Generated by Django 4.1.2 on 2022-11-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
