# Generated by Django 4.1.2 on 2022-12-02 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='body',
            new_name='comment',
        ),
    ]
