# Generated by Django 4.1.2 on 2022-12-02 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_post_comments_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='body',
        ),
    ]
